[package]
name = "partizee"
version = "0.1.0"
edition = "2024"
authors = ["MrDeadCe11 <mister.deadce11@gmail.com>"]
description = "A CLI tool to bootstrap partisia dapps"
license = "MIT"


[[bin]]
name = "Partizee"
path = "src/main.rs"

[dependencies]
cargo-partisia-contract = "5.204.0"
clap = "4.5.38"
cliclack = "0.3.6"
tera = "1.20.0"
tokio = { version = "1.45.0", features = ["full"] }
tokio-test = "0.4.4"
pbc_contract_common = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
pbc_contract_codegen = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
pbc_traits = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
pbc_lib = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
read_write_rpc_derive = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
read_write_state_derive = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
create_type_spec_derive = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }
pbc_zk = { git = "https://git@gitlab.com/partisiablockchain/language/contract-sdk.git", tag = "v.16.94.0" }

[features]
abi = ["pbc_contract_common/abi", "pbc_contract_codegen/abi", "pbc_traits/abi", "create_type_spec_derive/abi", "pbc_lib/abi"]

