[package]
name = "partizee"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[[bin]]
name = "partizee"
path = "src/main.rs"

[dependencies]
cargo-partisia-contract = { workspace = true }
clap = { workspace = true }
cliclack = { workspace = true }
tera = { workspace = true }
tokio = { workspace = true }
# tokio-test = { workspace = true }
pbc_contract_common = { workspace = true }
pbc_contract_codegen = { workspace = true }
pbc_traits = { workspace = true }
pbc_lib = { workspace = true }
read_write_rpc_derive = { workspace = true }
read_write_state_derive = { workspace = true }
create_type_spec_derive = { workspace = true }
pbc_zk = { workspace = true }
serde_json = { workspace = true }
getrandom = { workspace = true }
dirs = { workspace = true }
walkdir = { workspace = true }
base64 = "0.22.1"
serde = "1.0.219"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[features]
abi = ["pbc_contract_common/abi", "pbc_contract_codegen/abi", "pbc_traits/abi", "create_type_spec_derive/abi", "pbc_lib/abi"]

